[package]
name = "CODE"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
    "start1/hello_world",
    "start1/variables",
    "start1/authentication",
    "start1/login"
]
